// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function HandleModifier(arg1) {
  return window['go']['main']['App']['HandleModifier'](arg1);
}
