// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Config():Promise<main.Config>;

export function HandleModifier(arg1:number):Promise<string>;
